namespace CCL.Types.Proxies.Controls
{
    public enum VRButtonAlias
    {
        Undefined,
        TriggerHairline,
        TriggerTouch,
        TriggerPress,
        TriggerClick,
        GripHairline,
        GripTouch,
        GripPress,
        GripClick,
        TouchpadTouch,
        TouchpadPress,
        TouchpadTwoTouch,
        TouchpadTwoPress,
        ButtonOneTouch,
        ButtonOnePress,
        ButtonTwoTouch,
        ButtonTwoPress,
        StartMenuPress,
        TouchpadSense,
        TriggerSense,
        MiddleFingerSense,
        RingFingerSense,
        PinkyFingerSense,
        GripSense,
        GripSensePress
    }
}