namespace CCL.Types
{
    public enum BaseTrainCarType
    {
        NotSet,
        LocoShunter = 10,
        LocoSteamHeavy = 20,
        Tender,
        LocoS060 = 25,
        LocoRailbus = 30,
        LocoDiesel = 40,
        LocoDE6Slug = 45,
        LocoDH4 = 50,
        LocoDM3 = 60,
        LocoMicroshunter = 70,
        FlatbedEmpty = 200,
        FlatbedStakes,
        FlatbedMilitary,
        AutorackRed = 250,
        AutorackBlue,
        AutorackGreen,
        AutorackYellow,
        TankOrange = 300,
        TankWhite,
        TankYellow,
        TankBlue,
        TankChrome,
        TankBlack,
        TankShortMilk = 325,
        StockRed = 350,
        StockGreen,
        StockBrown,
        BoxcarBrown = 400,
        BoxcarGreen,
        BoxcarPink,
        BoxcarRed,
        BoxcarMilitary,
        RefrigeratorWhite = 450,
        HopperBrown = 500,
        HopperTeal,
        HopperYellow,
        GondolaRed = 550,
        GondolaGreen,
        GondolaGray,
        PassengerRed = 600,
        PassengerGreen,
        PassengerBlue,
        HandCar = 700,
        CabooseRed = 750,
        NuclearFlask = 800
    }

    public enum BaseCargoType
    {
        None,
        Coal = 20,
        IronOre,
        CrudeOil = 40,
        Diesel,
        Gasoline,
        Methane,
        Logs = 60,
        Boards,
        Plywood,
        Wheat = 80,
        Corn,
        SunflowerSeeds,
        Pigs = 100,
        Cows,
        Poultry,
        Sheep,
        Goats,
        Bread = 120,
        DairyProducts,
        MeatProducts,
        CannedFood,
        CatFood,
        LocalFruits,
        Vegetables,
        Milk,
        Eggs,
        Cotton,
        Wool,
        SteelRolls = 140,
        SteelBillets,
        SteelSlabs,
        SteelBentPlates,
        SteelRails,
        ScrapMetal = 150,
        ElectronicsIskar = 160,
        ElectronicsKrugmann,
        ElectronicsAAG,
        ElectronicsNovae,
        ElectronicsTraeg,
        ToolsIskar = 180,
        ToolsBrohm,
        ToolsAAG,
        ToolsNovae,
        ToolsTraeg,
        Furniture = 200,
        Pipes,
        ClothingObco = 220,
        ClothingNeoGamma,
        ClothingNovae,
        ClothingTraeg,
        Medicine = 240,
        ChemicalsIskar,
        ChemicalsSperex,
        NewCars = 260,
        ImportedNewCars,
        Tractors,
        Excavators,
        Alcohol = 280,
        Acetylene,
        CryoOxygen,
        CryoHydrogen,
        Argon,
        Nitrogen,
        Ammonia,
        SodiumHydroxide,
        SpentNuclearFuel = 300,
        Ammunition,
        Biohazard,
        Tanks = 320,
        MilitaryTrucks,
        MilitarySupplies,
        EmptySunOmni = 900,
        EmptyIskar,
        EmptyObco,
        EmptyGoorsk,
        EmptyKrugmann,
        EmptyBrohm,
        EmptyAAG,
        EmptySperex,
        EmptyNovae,
        EmptyTraeg,
        EmptyChemlek,
        EmptyNeoGamma,
        Passengers = 1000,
        Custom = 10000
    }

    public enum BaseResourceType
    {
        Fuel = 10,
        Sand = 11,
        Oil = 12,
        Water = 20,
        Coal = 21,
        ElectricCharge = 30,
        Car_DMG = 100,
        Cargo_DMG = 101,
        Wheels_DMG = 102,
        MechanicalPowertrain_DMG = 103,
        ElectricalPowertrain_DMG = 104,
        EnvironmentDamageCargo = 200,
        EnvironmentDamageFuel = 201,
        EnvironmentDamageCoal = 202
    }
}
