namespace CCL.Types
{
    public enum BaseTrainCarType
    {
        LocoDE2,
        LocoDE6,
        LocoDE6Slug,
        LocoDH4,
        LocoDM3,
        // Soon
        //LocoRailbus,
        LocoMicroshunter,
        LocoS060,
        LocoS282,
        S282Tender,
        Flatbed,
        FlatbedStakes,
        FlatbedMilitary,
        Autorack,
        TankGas,
        TankOil,
        TankChem,
        TankFood,
        Stock,
        Boxcar,
        BoxcarMilitary,
        Refrigerator,
        Hopper,
        Gondola,
        Passenger,
        NuclearFlask,
        Caboose,
        Handcar,
        Custom
    }

    public enum BaseCargoType
    {
        None,
        Coal = 20,
        IronOre,
        CrudeOil = 40,
        Diesel,
        Gasoline,
        Methane,
        Logs = 60,
        Boards,
        Plywood,
        Wheat = 80,
        Corn,
        SunflowerSeeds,
        Pigs = 100,
        Cows,
        Poultry,
        Sheep,
        Goats,
        Bread = 120,
        DairyProducts,
        MeatProducts,
        CannedFood,
        CatFood,
        LocalFruits,
        Vegetables,
        Milk,
        Eggs,
        Cotton,
        Wool,
        SteelRolls = 140,
        SteelBillets,
        SteelSlabs,
        SteelBentPlates,
        SteelRails,
        ScrapMetal = 150,
        ElectronicsIskar = 160,
        ElectronicsKrugmann,
        ElectronicsAAG,
        ElectronicsNovae,
        ElectronicsTraeg,
        ToolsIskar = 180,
        ToolsBrohm,
        ToolsAAG,
        ToolsNovae,
        ToolsTraeg,
        Furniture = 200,
        Pipes,
        ClothingObco = 220,
        ClothingNeoGamma,
        ClothingNovae,
        ClothingTraeg,
        Medicine = 240,
        ChemicalsIskar,
        ChemicalsSperex,
        NewCars = 260,
        ImportedNewCars,
        Tractors,
        Excavators,
        Alcohol = 280,
        Acetylene,
        CryoOxygen,
        CryoHydrogen,
        Argon,
        Nitrogen,
        Ammonia,
        SodiumHydroxide,
        SpentNuclearFuel = 300,
        Ammunition,
        Biohazard,
        Tanks = 320,
        MilitaryTrucks,
        MilitarySupplies,
        EmptySunOmni = 900,
        EmptyIskar,
        EmptyObco,
        EmptyGoorsk,
        EmptyKrugmann,
        EmptyBrohm,
        EmptyAAG,
        EmptySperex,
        EmptyNovae,
        EmptyTraeg,
        EmptyChemlek,
        EmptyNeoGamma,
        Passengers = 1000,
        Custom = 10000
    }

    public enum BaseResourceType
    {
        Fuel = 10,
        Sand = 11,
        Oil = 12,
        Water = 20,
        Coal = 21,
        ElectricCharge = 30,
        Car_DMG = 100,
        Cargo_DMG = 101,
        Wheels_DMG = 102,
        MechanicalPowertrain_DMG = 103,
        ElectricalPowertrain_DMG = 104,
        EnvironmentDamageCargo = 200,
        EnvironmentDamageFuel = 201,
        EnvironmentDamageCoal = 202
    }

    public enum DVTrainCarKind
    {
        Car,
        Caboose,
        Loco,
        Tender,
        Slug
    }
}
