using System.Linq;

namespace CCL.Types
{
    public static class ControlActions
    {
        public static readonly string[] NamesWithCategory =
        {
            "Movement/MoveHorizontal",
            "Movement/MoveVertical",
            "Movement/Crouch",
            "Movement/Run",
            "Movement/Sit",
            "Movement/Jump",
            "Movement/Lean",
            "Movement/Drop",
            "Movement/Place",
            "Movement/Teleport",
            "Movement/Zoom",
            "Movement/Scroll",
            "Movement/MouseLookHorizontal",
            "Movement/MouseLookVertical",
            "Movement/MouseLook (alt mode)",
            "Movement/AlternativeScroll",
            "Movement/TurnAround",

            "Train Controls/ThrottleIncremental",
            "Train Controls/ThrottleAbsolute",
            "Train Controls/BrakeIncremental",
            "Train Controls/BrakeAbsolute",
            "Train Controls/IndependentBrakeIncremental",
            "Train Controls/IndependentBrakeAbsolute",
            "Train Controls/ReverserIncremental",
            "Train Controls/ReverserAbsolute",
            "Train Controls/DynamicBrakeIncremental",
            "Train Controls/DynamicBrakeAbsolute",
            "Train Controls/BrakeCutoutIncremental",
            "Train Controls/BrakeCutoutAbsolute",
            "Train Controls/BrakeCutoutToggle",
            "Train Controls/HandbrakeIncremental",
            "Train Controls/HandbrakeAbsolute",
            "Train Controls/HandbrakeToggle",
            "Train Controls/CylCockIncremental",
            "Train Controls/CylCockAbsolute",
            "Train Controls/CylCockToggle",
            "Train Controls/SandIncremental",
            "Train Controls/SandAbsolute",
            "Train Controls/SandToggle",
            "Train Controls/WiperIncremental",
            "Train Controls/WiperAbsolute",
            "Train Controls/WiperToggle",
            "Train Controls/HeadlightFrontIncremental",
            "Train Controls/HeadlightFrontAbsolute",
            "Train Controls/HeadlightRearIncremental",
            "Train Controls/HeadlightRearAbsolute",
            "Train Controls/CabLightIncremental",
            "Train Controls/CabLightToggle",
            "Train Controls/GearAIncrement",
            "Train Controls/GearAAbsolute",
            "Train Controls/GearBIncrement",
            "Train Controls/GearBAbsolute",
            "Train Controls/HornIncremental",
            "Train Controls/Pantograph",
            "Train Controls/CabOrient",
            "Train Controls/BellIncremental",
            "Train Controls/BellAbsolute",
            "Train Controls/BellToggle",
            "Train Controls/ReleaseCyl",
            "Train Controls/FiredoorIncremental",
            "Train Controls/FiredoorAbsolute",
            "Train Controls/FiredoorToggle",
            "Train Controls/InjectorIncremental",
            "Train Controls/InjectorAbsolute",
            "Train Controls/InjectorToggle",
            "Train Controls/DraftIncremental",
            "Train Controls/DraftAbsolute",
            "Train Controls/DraftToggle",
            "Train Controls/BlowerIncremental",
            "Train Controls/BlowerAbsolute",
            "Train Controls/BlowerToggle",
            "Train Controls/BlowdownIncremental",
            "Train Controls/BlowdownAbsolute",
            "Train Controls/BlowdownToggle",
            "Train Controls/Shovel",
            "Train Controls/Lubricator",
            "Train Controls/AirPump",
            "Train Controls/Dynamo",
            "Train Controls/LightFire",
            "Train Controls/AshPan",
            "Train Controls/Couple",
            "Train Controls/Uncouple",
            "Train Controls/CouplerSelect",
            "Train Controls/Turntable",
            "Train Controls/Starter",
            "Train Controls/FuelCutoff",
            "Train Controls/StarterFuse",
            "Train Controls/TractionMotorFuse",
            "Train Controls/ElectricsFuse",

            "Item Interaction/InventorySlot1",
            "Item Interaction/InventorySlot2",
            "Item Interaction/InventorySlot3",
            "Item Interaction/InventorySlot4",
            "Item Interaction/InventorySlot5",
            "Item Interaction/InventorySlot6",
            "Item Interaction/InventorySlot7",
            "Item Interaction/InventorySlot8",
            "Item Interaction/InventorySlot9",
            "Item Interaction/InventorySlot10",
            "Item Interaction/InventorySlot11",
            "Item Interaction/InventorySlot12",
            "Item Interaction/InventoryOpen",
            "Item Interaction/InventoryQuickMoveModifier",
            "Item Interaction/InventoryQuickEquipModifier",
            "Item Interaction/FlipMultiplePagesModifier",
            "Item Interaction/FlipPage",
            "Item Interaction/Hotbar",

            "Other/InteractionPrimary",
            "Other/InteractionSecondary",
            "Other/InteractionMiddle",
            "Other/Interact",
            "Other/PhotoMode",
            "Other/HUD",
            "Other/ContextMenu",
            "Other/FirstPersonCam",
            "Other/ExternalCamFollow",
            "Other/ExternalCamUnfollow",
            "Other/Recenter",
            "Other/ToggleTrackingMode",
            "Other/Escape",

            "Console/Console"
        };
        public static readonly string[] Names =
{
            "MoveHorizontal",
            "MoveVertical",
            "Crouch",
            "Run",
            "Sit",
            "Jump",
            "Lean",
            "Drop",
            "Place",
            "Teleport",
            "Zoom",
            "Scroll",
            "MouseLookHorizontal",
            "MouseLookVertical",
            "MouseLook (alt mode)",
            "AlternativeScroll",
            "TurnAround",

            "ThrottleIncremental",
            "ThrottleAbsolute",
            "BrakeIncremental",
            "BrakeAbsolute",
            "IndependentBrakeIncremental",
            "IndependentBrakeAbsolute",
            "ReverserIncremental",
            "ReverserAbsolute",
            "DynamicBrakeIncremental",
            "DynamicBrakeAbsolute",
            "BrakeCutoutIncremental",
            "BrakeCutoutAbsolute",
            "BrakeCutoutToggle",
            "HandbrakeIncremental",
            "HandbrakeAbsolute",
            "HandbrakeToggle",
            "CylCockIncremental",
            "CylCockAbsolute",
            "CylCockToggle",
            "SandIncremental",
            "SandAbsolute",
            "SandToggle",
            "WiperIncremental",
            "WiperAbsolute",
            "WiperToggle",
            "HeadlightFrontIncremental",
            "HeadlightFrontAbsolute",
            "HeadlightRearIncremental",
            "HeadlightRearAbsolute",
            "CabLightIncremental",
            "CabLightToggle",
            "GearAIncrement",
            "GearAAbsolute",
            "GearBIncrement",
            "GearBAbsolute",
            "HornIncremental",
            "Pantograph",
            "CabOrient",
            "BellIncremental",
            "BellAbsolute",
            "BellToggle",
            "ReleaseCyl",
            "FiredoorIncremental",
            "FiredoorAbsolute",
            "FiredoorToggle",
            "InjectorIncremental",
            "InjectorAbsolute",
            "InjectorToggle",
            "DraftIncremental",
            "DraftAbsolute",
            "DraftToggle",
            "BlowerIncremental",
            "BlowerAbsolute",
            "BlowerToggle",
            "BlowdownIncremental",
            "BlowdownAbsolute",
            "BlowdownToggle",
            "Shovel",
            "Lubricator",
            "AirPump",
            "Dynamo",
            "LightFire",
            "AshPan",
            "Couple",
            "Uncouple",
            "CouplerSelect",
            "Turntable",
            "Starter",
            "FuelCutoff",
            "StarterFuse",
            "TractionMotorFuse",
            "ElectricsFuse",

            "InventorySlot1",
            "InventorySlot2",
            "InventorySlot3",
            "InventorySlot4",
            "InventorySlot5",
            "InventorySlot6",
            "InventorySlot7",
            "InventorySlot8",
            "InventorySlot9",
            "InventorySlot10",
            "InventorySlot11",
            "InventorySlot12",
            "InventoryOpen",
            "InventoryQuickMoveModifier",
            "InventoryQuickEquipModifier",
            "FlipMultiplePagesModifier",
            "FlipPage",
            "Hotbar",

            "InteractionPrimary",
            "InteractionSecondary",
            "InteractionMiddle",
            "Interact",
            "PhotoMode",
            "HUD",
            "ContextMenu",
            "FirstPersonCam",
            "ExternalCamFollow",
            "ExternalCamUnfollow",
            "Recenter",
            "ToggleTrackingMode",
            "Escape",

            "Console"
        };

        public static string RemoveCategory(string name)
        {
            return string.Join("/", name.Split('/').Skip(1));
        }
    }
}
